name: Size limit

on: [pull_request]

jobs:
  size:
    runs-on: ubuntu-latest

    env:
      CI_JOB_NUMBER: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use size limit
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
